NAME = VIOLENCE

CXX = c++

CXXFLAGS := -Wall -Wextra -Werror #-std=c++98

HEADERS = HumanA.hpp      HumanB.hpp      Weapon.hpp

SRCS = HumanA.cpp   HumanB.cpp  Weapon.cpp  main.cpp


all: $(HEADERS) $(NAME)

$(NAME):
	$(CXX) $(CXXFLAGS) $(SRCS) -o $(NAME)

